STATUS_UNPLAYED = "🟠 Never played"
STATUS_BACKLOG = "🔵 Backlog"
STATUS_PLAYING = "🟣 Playing"
STATUS_FINISHED = "🟢 Finished"

STATUSES = [
    STATUS_UNPLAYED,
    STATUS_BACKLOG,
    STATUS_PLAYING,
    STATUS_FINISHED,
]

SMART_PICK_STATUSES = [
    STATUS_BACKLOG,
    STATUS_UNPLAYED,
    STATUS_PLAYING,
]


SMART_PICK_SAMPLE_SIZE = 30

PAGE_SIZE = 200
GAMES_PER_ROW = 6
