STATUS_UNPLAYED = "🟠 Never played"
STATUS_BACKLOG = "🔵 Backlog"
STATUS_PLAYING = "🟣 Playing"
STATUS_FINISHED = "🟢 Finished"

STATUSES = [
    STATUS_UNPLAYED,
    STATUS_BACKLOG,
    STATUS_PLAYING,
    STATUS_FINISHED,
]

SMART_PICK_STATUSES = [
    STATUS_BACKLOG,
    STATUS_UNPLAYED,
    STATUS_PLAYING,
]

PAGE_SIZE = 198
GAMES_PER_ROW = 6

# Steam metadata cache/background refresh
METADATA_CACHE_MAX_AGE_DAYS = 90
METADATA_BACKGROUND_BATCH_SIZE = 10
METADATA_BACKGROUND_PAUSE_SECONDS = 2
METADATA_FAILED_RETRY_SECONDS = 60 * 60
METADATA_NETWORK_BACKOFF_SECONDS = 5 * 60
METADATA_RATE_LIMIT_BACKOFF_SECONDS = 15 * 60

# Persistent metadata fetch state
METADATA_STATE_DEFERRED = "deferred"
METADATA_STATE_METADATA_UNAVAILABLE = "metadata_unavailable"
METADATA_UNAVAILABLE_FIRST_RETRY_SECONDS = 24 * 60 * 60
METADATA_UNAVAILABLE_SECOND_RETRY_SECONDS = 7 * 24 * 60 * 60
METADATA_UNAVAILABLE_RECHECK_SECONDS = 30 * 24 * 60 * 60


# HowLongToBeat cache / name matching
HLTB_MATCHER_VERSION = 8
HLTB_MATCH_AUTO_SIMILARITY = 0.90
HLTB_MATCH_MIN_SIMILARITY = 0.75
HLTB_CACHE_MAX_AGE_DAYS = 180
HLTB_NO_MATCH_CACHE_DAYS = 30

# HowLongToBeat background population
HLTB_BACKGROUND_PAUSE_SECONDS = 1
HLTB_BACKGROUND_PROGRESS_INTERVAL = 10
HLTB_ERROR_BACKOFF_SECONDS = 5
HLTB_REPEATED_ERROR_BACKOFF_SECONDS = 10
